=== pypi-data/pypi-mirror-212/packages/opentrons-shared-data/opentrons_shared_data-6.3.1-py2.py3-none-any.whl/opentrons_shared_data/data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "xyzArray": {
      "type": "array",
      "description": "Array of 3 numbers, [x, y, z]",
      "items": { "type": "number" },
      "minItems": 3,
      "maxItems": 3
    },
    "liquidHandlingSpecs": {
      "description": "Object containing linear equations for translating between uL of liquid and mm of plunger travel. There is one linear equation for aspiration and one for dispense",
      "type": "object",
      "required": ["aspirate", "dispense"],
      "additionalProperties": false,
      "properties": {
        "aspirate": { "$ref": "#/definitions/xyzArray" },
        "dispense": { "$ref": "#/definitions/xyzArray" }
      }
    },
    "flowRate": {
      "type": "object",
      "required": ["value", "min", "max"],
      "properties": {
        "value": {
          "$ref": "#/definitions/positiveNumber",
          "$comment": "This key is deprecated in favor of valuesByApiLevel"
        },
        "min": { "$ref": "#/definitions/positiveNumber" },
        "max": { "$ref": "#/definitions/positiveNumber" }
      }
    }
  },
  "type": "object",
  "required": [
    "$otSharedSchema",
    "maxVolume",
    "minVolume",
    "defaultTipracks",
    "supportedTips"
  ],
  "additionalProperties": false,
  "properties": {
    "$otSharedSchema": {
      "type": "string",
      "description": "The path to a valid Opentrons shared schema relative to the shared-data directory, without its extension. For instance, #/pipette/schemas/2/pipetteLiquidPropertiesSchema.json is a reference to this schema."
    },
    "supportedTips": {
      "type": "object",
      "description": "A container of supported tip types",
      "properties": {
        "patternProperties": {
          "description": "Tip specific liquid handling properties for a given pipette. Using the active tip on a pipette, we will look up the pipetting configurations associated with that tip+pipette combo.",
          "type": "object",
          "$comment": "Example key: 't50'",
          "^t[0-9]{2,4}": {
            "required": [
              "defaultAspirateFlowRate",
              "defaultDispenseFlowRate",
              "defaultBlowOutFlowRate",
              "aspirate",
              "dispense"
            ],
            "properties": {
              "defaultAspirateFlowRate": {
                "$ref": "#/definitions/flowRate"
              },
              "defaultDispenseFlowRate": {
                "$ref": "#/definitions/flowRate"
              },
              "defaultBlowOutFlowRate": {
                "$ref": "#/definitions/flowRate"
              },
              "defaultTipLength": {
                "$ref": "#/definitions/positiveNumber"
              },
              "defaultTipOverlap": {
                "$ref": "#/definitions/positiveNumber"
              },
              "defaultReturnTipHeight": {
                "$ref": "#/definitions/positiveNumber"
              },
              "aspirate": {
                "type": "array",
                "items": { "$ref": "#/definitions/liquidHandlingSpecs" }
              },
              "dispense": {
                "type": "array",
                "items": { "$ref": "#/definitions/liquidHandlingSpecs" }
              }
            }
          }
        }
      }
    },
    "maxVolume": { "$ref": "#/definitions/positiveNumber" },
    "minVolume": { "$ref": "#/definitions/positiveNumber" },
    "defaultTipracks": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== pypi-data/pypi-mirror-212/packages/opentrons-shared-data/opentrons_shared_data-6.3.1-py2.py3-none-any.whl/opentrons_shared_data/data/pipette/definitions/2/liquid/single_channel/p300/1_4.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t200": {
      "defaultAspirateFlowRate": 150.0,
      "defaultDispenseFlowRate": 300.0,
      "defaultBlowOutFlowRate": 1000.0,
      "defaultTipLength": 51.7,
      "defaultTipOverlap": 7.47,
      "defaultReturnTipHeight": null,
      "aspirate": {
        "opentrons/tipone_96_tiprack_200ul/1": [
          [36.19844973, 0.043, 16.548],
          [54.98518519, 0.012, 17.658],
          [73.90077516, 0.008, 17.902],
          [111.8437953, 0.004, 18.153],
          [302.3895337, 0.001, 18.23]
        ],
        "opentrons/opentrons_96_filtertiprack_200ul/1": [
          [36.19844973, 0.043, 16.548],
          [54.98518519, 0.012, 17.658],
          [73.90077516, 0.008, 17.902],
          [111.8437953, 0.004, 18.153],
          [302.3895337, 0.001, 18.23]
        ],
        "default": [
          [36.19844973, 0.043, 16.548],
          [54.98518519, 0.012, 17.658],
          [73.90077516, 0.008, 17.902],
          [111.8437953, 0.004, 18.153],
          [302.3895337, 0.001, 18.23]
        ]
      },
      "dispense": {
        "opentrons/tipone_96_tiprack_200ul/1": [
          [302.3895337, 0.0, 18.83156277]
        ],
        "opentrons/opentrons_96_filtertiprack_200ul/1": [
          [302.3895337, 0.0, 18.83156277]
        ],
        "default": [[302.3895337, 0.0, 18.83156277]]
      },
      "defaultTipOverlapDictionary": {
        "opentrons/tipone_96_tiprack_200ul/1": 6.1,
        "opentrons/opentrons_96_filtertiprack_200ul/1": 7.47
      }
    },
    "t300": {
      "defaultAspirateFlowRate": 150.0,
      "defaultDispenseFlowRate": 300.0,
      "defaultBlowOutFlowRate": 1000.0,
      "defaultTipLength": 51.7,
      "defaultTipOverlap": 7.47,
      "defaultReturnTipHeight": null,
      "aspirate": {
        "opentrons/opentrons_96_tiprack_300ul/1": [
          [36.19844973, 0.043, 16.548],
          [54.98518519, 0.012, 17.658],
          [73.90077516, 0.008, 17.902],
          [111.8437953, 0.004, 18.153],
          [302.3895337, 0.001, 18.23]
        ],
        "default": [
          [36.19844973, 0.043, 16.548],
          [54.98518519, 0.012, 17.658],
          [73.90077516, 0.008, 17.902],
          [111.8437953, 0.004, 18.153],
          [302.3895337, 0.001, 18.23]
        ]
      },
      "dispense": {
        "opentrons/opentrons_96_tiprack_300ul/1": [
          [302.3895337, 0.0, 18.83156277]
        ],
        "default": [[302.3895337, 0.0, 18.83156277]]
      },
      "defaultTipOverlapDictionary": {
        "opentrons/opentrons_96_tiprack_300ul/1": 7.47
      }
    }
  },
  "maxVolume": 300,
  "minVolume": 30.0,
  "defaultTipracks": [
    "opentrons/opentrons_96_tiprack_300ul/1",
    "opentrons/opentrons_96_filtertiprack_200ul/1"
  ]
}

=== pypi-data/pypi-mirror-212/packages/opentrons-shared-data/opentrons_shared_data-6.3.1-py2.py3-none-any.whl/opentrons_shared_data/data/pipette/definitions/2/liquid/eight_channel/p10/1_6.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t10": {
      "defaultAspirateFlowRate": 5.0,
      "defaultDispenseFlowRate": 10.0,
      "defaultBlowOutFlowRate": 1000.0,
      "defaultTipLength": 33.0,
      "defaultTipOverlap": 3.29,
      "defaultReturnTipHeight": null,
      "aspirate": {
        "opentrons/opentrons_96_tiprack_10ul/1": [
          [0.8649, 0.0374, 0.8484],
          [1.2416, -0.0987, 0.9503],
          [1.6053, -0.069, 0.9134],
          [1.9851, -0.0226, 0.839],
          [2.3481, -0.0313, 0.8561],
          [2.7207, -0.0143, 0.8164],
          [3.0702, -0.028, 0.8536],
          [4.5998, -0.0006, 0.7694],
          [6.1063, -0.0022, 0.7769],
          [7.6504, 0.0011, 0.7564],
          [9.1863, 0.0003, 0.7626],
          [10.7574, 0.0018, 0.7488],
          [12.2984, -0.4986, 6.1321]
        ],
        "opentrons/opentrons_96_filtertiprack_10ul/1": [
          [0.8649, 0.0374, 0.8484],
          [1.2416, -0.0987, 0.9503],
          [1.6053, -0.069, 0.9134],
          [1.9851, -0.0226, 0.839],
          [2.3481, -0.0313, 0.8561],
          [2.7207, -0.0143, 0.8164],
          [3.0702, -0.028, 0.8536],
          [4.5998, -0.0006, 0.7694],
          [6.1063, -0.0022, 0.7769],
          [7.6504, 0.0011, 0.7564],
          [9.1863, 0.0003, 0.7626],
          [10.7574, 0.0018, 0.7488],
          [12.2984, -0.4986, 6.1321]
        ],
        "opentrons/geb_96_tiprack_10ul/1": [
          [0.8649, 0.0374, 0.8484],
          [1.2416, -0.0987, 0.9503],
          [1.6053, -0.069, 0.9134],
          [1.9851, -0.0226, 0.839],
          [2.3481, -0.0313, 0.8561],
          [2.7207, -0.0143, 0.8164],
          [3.0702, -0.028, 0.8536],
          [4.5998, -0.0006, 0.7694],
          [6.1063, -0.0022, 0.7769],
          [7.6504, 0.0011, 0.7564],
          [9.1863, 0.0003, 0.7626],
          [10.7574, 0.0018, 0.7488],
          [12.2984, -0.4986, 6.1321]
        ],
        "opentrons/eppendorf_96_tiprack_10ul_eptips/1": [
          [0.8649, 0.0374, 0.8484],
          [1.2416, -0.0987, 0.9503],
          [1.6053, -0.069, 0.9134],
          [1.9851, -0.0226, 0.839],
          [2.3481, -0.0313, 0.8561],
          [2.7207, -0.0143, 0.8164],
          [3.0702, -0.028, 0.8536],
          [4.5998, -0.0006, 0.7694],
          [6.1063, -0.0022, 0.7769],
          [7.6504, 0.0011, 0.7564],
          [9.1863, 0.0003, 0.7626],
          [10.7574, 0.0018, 0.7488],
          [12.2984, -0.4986, 6.1321]
        ],
        "default": [
          [0.8649, 0.0374, 0.8484],
          [1.2416, -0.0987, 0.9503],
          [1.6053, -0.069, 0.9134],
          [1.9851, -0.0226, 0.839],
          [2.3481, -0.0313, 0.8561],
          [2.7207, -0.0143, 0.8164],
          [3.0702, -0.028, 0.8536],
          [4.5998, -0.0006, 0.7694],
          [6.1063, -0.0022, 0.7769],
          [7.6504, 0.0011, 0.7564],
          [9.1863, 0.0003, 0.7626],
          [10.7574, 0.0018, 0.7488],
          [12.2984, -0.4986, 6.1321]
        ]
      },
      "dispense": {
        "opentrons/opentrons_96_tiprack_10ul/1": [
          [12.74444519, 0.0, 0.8058688085]
        ],
        "opentrons/opentrons_96_filtertiprack_10ul/1": [
          [12.74444519, 0.0, 0.8058688085]
        ],
        "opentrons/geb_96_tiprack_10ul/1": [[12.74444519, 0.0, 0.8058688085]],
        "opentrons/eppendorf_96_tiprack_10ul_eptips/1": [
          [12.74444519, 0.0, 0.8058688085]
        ],
        "default": [[12.74444519, 0.0, 0.8058688085]]
      },
      "defaultTipOverlapDictionary": {
        "opentrons/opentrons_96_tiprack_10ul/1": 3.29,
        "opentrons/opentrons_96_filtertiprack_10ul/1": 3.29,
        "opentrons/geb_96_tiprack_10ul/1": 6.2,
        "opentrons/eppendorf_96_tiprack_10ul_eptips/1": 1.0
      }
    }
  },
  "maxVolume": 10,
  "minVolume": 1.0,
  "defaultTipracks": [
    "opentrons/opentrons_96_tiprack_10ul/1",
    "opentrons/opentrons_96_filtertiprack_10ul/1",
    "opentrons/geb_96_tiprack_10ul/1"
  ]
}
